version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      PYTHONPATH: /app
    command: python frameworks/flask_app.py
